### PR TITLE
fix(yew-notifications): Update yew to latest version (0.21.0)

### PR DESCRIPTION
**Pull request by orangethewell**
This pull request fixes compatibility with latest yew version and increments minor version of the crate in 1.

### CODE REVIEW

**Comment by TheBestTvarynka** [comment]
Hi
Thank you for your contribution. Please, fix formatting 🥺 

I'll have a look at it today (around the evening). I wanna perform a few tests

**Comment by orangethewell** [comment]
No problem, I'll fix it. I just don't know exactly what the problem is, is it because there is a line break? I have never used cargo-fmt

**Comment by orangethewell** [comment]
No problem, I'll fix it. I just don't know exactly what the problem is, is it because there is a line break? I have never used cargo-fmt

**Comment by TheBestTvarynka** [comment]
just run `cargo +nightly fmt --all` in the terminal. It will do everything we need. If you get an error, then try to run `rustup toolchain install nightly`

**Comment by TheBestTvarynka** [comment]
relaced with #7 

I'm closing this PR for now. But thank you for your attention to this project anyway. I decided to do it by myself because I also need to fix the code and update other dependencies

**Pull request closed without merging**
